script: 'ci/travis.rb'
rvm:
  - ree
env:
  - "GEM=railties"
  - "GEM=ap,am,amo,ares,as"
  - "GEM=ar:mysql"
  - "GEM=ar:mysql2"
  - "GEM=ar:sqlite3"
notifications:
  email: true
bundler_args: --path vendor/bundle
